name: Build and Deploy
on:
  push:
    branches:
      - feature/static-docs
    paths: ['**/*.tsx'] # Trigger the action only when files change in the folders defined here
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_BASE_PATH: /mocker
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
      - name: Install and Build
        #working-directory: ./web
        run: | # Install npm packages and build the Storybook files
          npm ci
          npm run build:static
      - name: Add .nojekyll file
        run: touch ./out/.nojekyll
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: docs # The branch the action should deploy to.
          folder: out # The folder that the build-storybook script generates files.
          clean: true # Automatically remove deleted files from the deploy branch
          clean-exclude: |
            .gitignore
            docs/.gitkeep
          target-folder: docs # The folder that we serve our Storybook files from
          token: ${{ secrets.GITHUB_TOKEN }}
